CPPFLAGS += -Wno-deprecated-declarations
#CPPFLAGS += -DDEBUG
ARDUINO_LIBS = Mutila SoftwareSerial

# Hardware selection (uncomment as appropriate)
#BOARD_TAG = uno

# For a modern nano:
BOARD_TAG = nano
BOARD_SUB = atmega328

# For a pro mini:
#BOARD_TAG = pro5v328

include arduino.mk

