# For now these examples are excluded as they are known not to
# work with the ESP build...
EXCLUDED_EXAMPLES = DFPlayerMini/ DFPReader/

EXAMPLES = $(filter-out $(EXCLUDED_EXAMPLES),$(wildcard */))
SUBDIRSCLEAN = $(addsuffix clean,$(EXAMPLES))
SUBDIRSBUILD = $(addsuffix build,$(EXAMPLES))

.PHONY: clean all

all: $(SUBDIRSBUILD)
	@echo "build OK"

clean: $(SUBDIRSCLEAN)

%build: %
	$(MAKE) -f Makefile.esp -C $<

%clean: %
	$(MAKE) -f Makefile.esp -C $< clean
	
