CPPFLAGS += -Wno-unused-variable -Wno-deprecated-declarations -Wno-cpp -Wno-write-strings
CPPFLAGS += -DDEBUG
ARDUINO_LIBS = Mutila DFPlayer_Mini_Mp3 SoftwareSerial
BOARD_TAG = pro
BOARD_SUB = 16MHzatmega328

include ../arduino.mk
