CPPFLAGS += -Wno-unused-variable -Wno-deprecated-declarations -Wno-cpp -Wno-write-strings
CPPFLAGS += -DDEBUG -DMUTILADEBUG
ARDUINO_LIBS = Mutila
BOARD_TAG = nano
BOARD_SUB = atmega328

include ../arduino.mk


