CPPFLAGS += -Wno-unused-variable -Wno-deprecated-declarations -Wno-cpp -Wno-write-strings
CPPFLAGS += -DDEBUG -DMUTILADEBUG
ARDUINO_LIBS = Mutila Adafruit_NeoPixel
BOARD_TAG = uno

include ../arduino.mk


